### ISSUE TITLE
Natalizumab is split into two cliques

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Babel#157]
As per [NodeNorm on RENCI dev](https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=MESH%3AD000069442&curie=CHEMBL.COMPOUND%3ACHEMBL1201607&conflate=true), Natalizumab is split into two clades: [MESH:D000069442](http://id.nlm.nih.gov/mesh/D000069442) and [CHEMBL.COMPOUND:CHEMBL1201607](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1201607/). We should figure out why this is the case, and how we can combine these two cliques.

**Comment by ShervinAbd92** [comment]
hi @gaurav any updates on this issue?

**Comment by gaurav** [comment]
We now combine this into [a single clique](https://nodenormalization-sri.renci.org/1.5/get_normalized_nodes?curie=MESH%3AD000069442&curie=CHEMBL.COMPOUND%3ACHEMBL1201607&conflate=true&drug_chemical_conflate=false&description=false) with a preferred ID of [UNII:3JB47N2Q2P "natalizumab"](https://precision.fda.gov/uniisearch/srs/unii/3JB47N2Q2P), even with drug conflation turned off. Closing.
