### ISSUE TITLE
UBERON:0002104 not merged with UMLS:C3536733 in 2023jul9

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Babel#170]
It was merged in previous releases.

**Comment by cbizon** [comment]
So here's something I'm very confused about.  I am running on the "drugs" branch.    I have the same code on my laptop and on hatteras.   I have run anatomy in both places.  On my laptop, these are merged, on hatteras they are not.  I have checked and the intermediate files appear to be the same in both cases (at least by filesize).

The only difference I can think of are maybe library versions across the two environments?

**Comment by gaurav** [comment]
It might be worth running `pip freeze` in both locations to see if one of the prerequisites are out of sync, but I agree that’s not very likely. The likeliest cause is that one of the SnakeMake targets doesn’t have its prerequisites declared correctly, so that one of the runs ran the conflation after the UBERON concord (or some other critical input file) had been generated, while the other ran it before that file had been generated. By the time SnakeMake finished, all files would have been generated, so you wouldn’t see a difference in the input files. The logs might shed some light on this, but manually checking the prerequisites working backwards from the conflation might be enough to spot the culprit.

**Comment by cbizon** [comment]
Smart idea - to try it out, I went to hatteras where the merge was not happening and rebuilt just the compendia.  In the above scenario, I think that this should have allowed the merger to take place, but it did not :(
