### ISSUE TITLE
Information Content values broken in UberGraph

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Babel#192]
All IC values from UberGraph are NaNs: either +Inf, -Inf, +NaN or -NaN (https://api.triplydb.com/s/tZYctbg73).

Tracked at UberGraph at https://github.com/INCATools/ubergraph/issues/132

Example: https://api.triplydb.com/s/hVKIV_tKG

**Comment by balhoff** [comment]
Hey @gaurav, I've been trying to get that fixed over the last couple days, and now it's done!

**Comment by gaurav** [comment]
Thanks, Jim! It's working great now.
