### ISSUE TITLE
Allow running of disease_phenotype.py without UMLS license

### ISSUE THREAD

**Issue by kshefchek** [TranslatorSRI/Babel#24]
This is likely already on the radar - but it would be useful to be able to run the disease_phenotype parser without a UMLS license

**Comment by gaurav** [comment]
Babel now requires that you put a few files that can't be downloaded by the software into the `input_data/private` directory (see [README](https://github.com/TranslatorSRI/Babel#readme) for details). At the moment this is MRCONSO.RRF and MRSTY.RRF from UMLS (which requires the user to create an account to access the UMLS datasets) and the [FDA UNII datasets](https://precision.fda.gov/uniisearch/archive) (but these are going to be removed from here, see https://github.com/TranslatorSRI/Babel/issues/76). Does this meet the needs of this issue?

**Comment by cbizon** [comment]
I don't think we can do much better than this.

**Comment by matentzn** [comment]
It would really be good if translator monarch tims and OMOP would try to lobby UMLS for a public dump of all codes and mappings at least.

**Comment by gaurav** [comment]
I'm going to close this as something we can't do much about, but I agree @matentzn that lobbying UMLS to make a public dump of all codes and mappings would be great! I think a bunch of the licensing issues are around SNOMED; I wonder if they could be convinced to publish a public dataset that only includes NCIt + ontology mappings or something. Alternatively, we could consider building an external resource that puts all the NCIt mappings we know about in one place.
