### ISSUE TITLE
Remove special handling of Polypeptide and ChemicalEntity prefixes

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Babel#263]
We have a couple of special cases for handling prefixes for `biolink:Polypeptide` and `biolink:ChemicalEntity`:

https://github.com/TranslatorSRI/Babel/blob/78bf0f7f039f897dabb73768d21c010c87a85757/src/node.py#L312-L316

However, both  [`biolink:Polypeptide`](https://biolink.github.io/biolink-model/Polypeptide/#valid-id-prefixes) and [`biolink:ChemicalEntity`](https://biolink.github.io/biolink-model/ChemicalEntity/#valid-id-prefixes) have reasonable looking prefixes now.

@cbizon Should we remove these special cases?

**Comment by cbizon** [comment]
Yes, I think we should
