### ISSUE TITLE
Is UMLS:C0002712 a Protein?

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/Babel#40]
right now this identifier (Amylases) gets a class of Protein.  But shouldn't it be ProteinFamily?

**Comment by gaurav** [comment]
As of the 2022sep6 release, this identifier is now classified as a `biolink:ChemicalEntity` and no longer classified as a `biolink:Protein` (https://nodenormalization-dev.apps.renci.org/1.3/get_normalized_nodes?curie=UMLS%3AC0002712&conflate=true). Is that sufficient to close this issue?
