### ISSUE TITLE
Valsartan not merging UMLS/PUBCHEM

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/Babel#51]
We appear to have some incomplete merging of UMLS  and PUBCHEM identifiers.  See e.g. Valsartan

**Comment by cbizon** [comment]
According to @gaurav this is fixed in dev, so hopefully we can get this rolled out soon.

**Comment by gaurav** [comment]
Fixed in Babel release 2022sep13 and deployed to RENCI-dev at https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=UMLS:C0216784. Closing.
