### ISSUE TITLE
Move KGX transform from NN to Babel

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/Babel#61]
We have at least one consumer of babel output that wants KGX format.  We have a KGX converter, but it lives in nodenorm for some reason.  It should be extracted from there and put over here and generation of KGX outputs should be made part of the build process.

**Comment by cbizon** [comment]
The KGX file that gets created makes a node for every identifier, and an edge between equivalent identifiers.   What should we do about conflation?   Maybe it makes sense to first conflate at the (normal file) output level, so we make a GeneProtein.txt concordance based on Gene.txt and Protein.txt and the Gene/Protein conflation.  Then the GeneProtein concordance can go through the same translator into KGX files and the consumer can decide if they want the conflated or unconflated ones.

**Comment by gaurav** [comment]
This is done in PR #206. Closing.
