### ISSUE TITLE
Stray empty line in umls.txt

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/Babel#62]
The UMLS concordance starts with a single blank line (causing trouble for the kgx transformer)

**Comment by gaurav** [comment]
This is the blank line I add so that Snakemake doesn't time out waiting for the output file to be created >.< I will look into a better way of doing this.

**Comment by cbizon** [comment]
could you touch the file which makes an empty (no newline character) file?

**Comment by gaurav** [comment]
Yup, touching the file instead of adding a blank line! Thanks. Closing.
