### ISSUE TITLE
Prefixes in ChemicalEntity aren't ordered in the same order as in Biolink

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Babel#68]
I noticed that the ChemicalEntity compendium has prefixes that are not [included in the list of identifier prefixes](https://biolink.github.io/biolink-model/docs/ChemicalEntity.html#identifier-prefixes) for biolink:ChemicalEntity. Some examples:
- PUBCHEM.COMPOUND
- INCHIKEY
- HMDB
- DRUGBANK

There may be others.

**Comment by gaurav** [comment]
After discussing this with @cbizon, it turns out that Babel defines the identifier prefixes for `biolink:ChemicalEntity` as the [list of prefixes for biolink:ChemicalEntity](https://biolink.github.io/biolink-model/docs/ChemicalEntity.html#identifier-prefixes) followed by the [list of prefixes for `SmallMolecule`](https://biolink.github.io/biolink-model/docs/SmallMolecule.html#identifier-prefixes), as per the code below:

https://github.com/TranslatorSRI/Babel/blob/7536b2593bba01e007af9f5e1c1156460c1415fd/src/node.py#L98-L100

Unfortunately, there's a `set()` in the middle of that statement, which means that the list of prefixes gets resorted, which is how we end up with a situation like [`PUBCHEM.COMPOUND:148951136`](https://nodenormalization-dev.apps.renci.org/get_normalized_nodes?curie=PUBCHEM.COMPOUND:148951136&conflate=false) (a.k.a. [AKOS012811781](https://pubchem.ncbi.nlm.nih.gov/substance/148951136)), which has a primary identifier of an INCHIKEY rather than the PUBCHEM.COMPOUND identifier.

I'll fix that by removing the set(). I'm not sure if there's a downside to leaving the ChemicalEntity + SmallMolecule prefix logic in, but since we don't have a compelling reason to change that, I propose we leave that unchanged.

**Comment by cbizon** [comment]
Is biolink the right place to fix this? i.e. should we make a PR to get the C.E. prefixes how we want them?

**Comment by gaurav** [comment]
I don't think we have a specific reason to change C.E. prefixes right now -- because of the bug in the prefix code, we're not currently handling ChemicalEntity prefixes correctly (PR https://github.com/TranslatorSRI/Babel/pull/94 should fix this). I like the idea of preferring ChemicalEntity identifiers if one is present, and otherwise defaulting to SmallMolecule identifiers. If we run into other ChemicalEntity prefix issues even after fixing this bug, we can tackle that in a separate issue -- in which case, yes, we should definitely fix that in Biolink rather than in Babel.
