### ISSUE TITLE
PubChem identifiers being split between SmallMolecule and MolecularMixture

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Babel#83]
As far as I can tell, this is because there are now two PubChem entries for water:
- https://pubchem.ncbi.nlm.nih.gov/compound/962 (type biolink:SmallMolecule)
- https://pubchem.ncbi.nlm.nih.gov/compound/22247451 (type: biolink:MolecularMixture)

Since the two PubChems are of different types, this triggers this piece of logic from chemical.py:
https://github.com/TranslatorSRI/Babel/blob/cc3db38233fbd5ea6a124d65dc91306941ac5493/src/createcompendia/chemicals.py#L529-L538

And water is changed from a biolink:SmallMolecule (in Babel 2022sep13) to biolink:ChemicalEntity (in Babel 2022oct13).

This should give us `UNII:059QF0KO0R` as the preferred ID; however, for some reason, [Babel 2022oct13 gives us `HMDB:HMDB0002111`](https://nodenormalization-dev.apps.renci.org/1.3/get_normalized_nodes?curie=MESH%3AD014867), even though `HMDB` isn't even on [the list of prefixes for ChemicalEntity](https://biolink.github.io/biolink-model/docs/ChemicalEntity.html#identifier-prefixes). So there's probably a second bug lurking in here somewhere.

**Comment by gaurav** [comment]
Chris thinks that ChemicalEntity prefixes are hardcoded in Babel somewhere.

**Comment by gaurav** [comment]
It turns out that there are 8,178 examples of this happening in Babel 2022oct13 of between 2 and 19 identifiers, all of which are of type {'biolink:SmallMolecule', 'biolink:MolecularMixture'}. (Here is [a badly formatted file](https://github.com/TranslatorSRI/Babel/files/9964757/pubchem.types.txt) with all the identifiers). All but 9 of these have an InChIKey, and so appear to be grouped by an InChIKey collision. 

Possible solutions:
1. Some of these collisions (but not all) could be resolved by removing InChIKey IDs.
2. We could force mixtures that evaluate as {'biolink:SmallMolecule', 'biolink:MolecularMixture'} to `biolink:MolecularMixture`, but that would include water.
3. We could tweak the custom prefixes for chemicals so that water goes back from `HMDB:HMDB0002111` to `PUBCHEM.COMPOUND:962` (see node.py code snippet below)

https://github.com/TranslatorSRI/Babel/blob/075b32cf8e323ee0c9007eaf715a4741ae382dd5/src/node.py#L85-L109

<details><summary>Some example identifiers</summary>
The nine cliques without InChIKeys are:

* Nickel boride ([PUBCHEM.COMPOUND:82791](https://pubchem.ncbi.nlm.nih.gov/compound/82791) and Nickel boride (Ni3B) [PUBCHEM.COMPOUND:6336855](https://pubchem.ncbi.nlm.nih.gov/compound/6336855)), InChIKey collision:
  > {'UMLS:C0628420', 'CAS:12007-02-2', 'CAS:12619-90-8', 'CAS:12007-00-0', 'PUBCHEM.COMPOUND:82791', 'MESH:C049893', 'PUBCHEM.COMPOUND:6336855'}) 	(2)	{'biolink:SmallMolecule', 'biolink:MolecularMixture'}
* [PUBCHEM.COMPOUND:166138](https://pubchem.ncbi.nlm.nih.gov/compound/166138) and [PUBCHEM.COMPOUND:166137](https://pubchem.ncbi.nlm.nih.gov/compound/166137), no InChIKey collision:
  > frozenset({'PUBCHEM.COMPOUND:166138', 'PUBCHEM.COMPOUND:166137', 'MESH:C407145', 'CAS:70236-51-0', 'UMLS:C0913820'}) 	(2)	{'biolink:SmallMolecule', 'biolink:MolecularMixture'}
* [PUBCHEM.COMPOUND:9572776](https://pubchem.ncbi.nlm.nih.gov/compound/9572776) and [PUBCHEM.COMPOUND:54609060](https://pubchem.ncbi.nlm.nih.gov/compound/54609060), no InChIKey collision:
  > frozenset({'CAS:5401-69-4', 'PUBCHEM.COMPOUND:9572776', 'PUBCHEM.COMPOUND:54609060'}) 	(2)	{'biolink:SmallMolecule', 'biolink:MolecularMixture'}
* [PUBCHEM.COMPOUND:12272670](https://pubchem.ncbi.nlm.nih.gov/compound/12272670) and [PUBCHEM.COMPOUND:9573653](https://pubchem.ncbi.nlm.nih.gov/compound/9573653), no InChIKey collision:
  > frozenset({'MESH:C006076', 'CAS:50471-02-8', 'CAS:52237-22-6', 'PUBCHEM.COMPOUND:12272670', 'PUBCHEM.COMPOUND:9573653', 'UMLS:C0070490'}) 	(2)	{'biolink:SmallMolecule', 'biolink:MolecularMixture'}
* [PUBCHEM.COMPOUND:163409081](https://pubchem.ncbi.nlm.nih.gov/compound/163409081) and [PUBCHEM.COMPOUND:163358784](https://pubchem.ncbi.nlm.nih.gov/compound/163358784), no InChIKey collision:
  > frozenset({'PUBCHEM.COMPOUND:163409081', 'UNII:83BU3492RP', 'PUBCHEM.COMPOUND:163358784', 'CAS:2647442-13-3', 'MESH:C000722705', 'PUBCHEM.COMPOUND:162625114'}) 	(2)	{'biolink:SmallMolecule', 'biolink:MolecularMixture'}
* [PUBCHEM.COMPOUND:16132438](https://pubchem.ncbi.nlm.nih.gov/compound/16132438) and [PUBCHEM.COMPOUND:118984450](https://pubchem.ncbi.nlm.nih.gov/compound/118984450), no InChIKey collision:
  > frozenset({'UMLS:C0293359', 'CHEMBL.COMPOUND:CHEMBL1201538', 'MESH:D061268', 'DrugCentral:5002', 'PUBCHEM.COMPOUND:16132438', 'UMLS:C5389884', 'DRUGBANK:DB00046', 'PUBCHEM.COMPOUND:118984450', 'UMLS:C0982221', 'CAS:133107-64-9'}) 	(2)	{'biolink:SmallMolecule', 'biolink:MolecularMixture'}
* [PUBCHEM.COMPOUND:156597127](https://pubchem.ncbi.nlm.nih.gov/compound/156597127) and [PUBCHEM.COMPOUND:75972517](https://pubchem.ncbi.nlm.nih.gov/compound/75972517), no InChIKey collision:
  > frozenset({'PUBCHEM.COMPOUND:156597127', 'PUBCHEM.COMPOUND:75972517', 'CAS:1323151-45-6'}) 	(2)	{'biolink:SmallMolecule', 'biolink:MolecularMixture'}
* [PUBCHEM.COMPOUND:16132344](https://pubchem.ncbi.nlm.nih.gov/compound/16132344) and [PUBCHEM.COMPOUND:121494108](https://pubchem.ncbi.nlm.nih.gov/compound/121494108), no InChIKey collision:
  > frozenset({'CAS:79804-71-0', 'PUBCHEM.COMPOUND:16132344', 'CAS:121249-14-7', 'PUBCHEM.COMPOUND:121494108', 'MESH:C085671'}) 	(2)	{'biolink:SmallMolecule', 'biolink:MolecularMixture'}
* [PUBCHEM.COMPOUND:16235945](https://pubchem.ncbi.nlm.nih.gov/compound/16235945) and [PUBCHEM.COMPOUND:10313238](https://pubchem.ncbi.nlm.nih.gov/compound/10313238), no InChIKey collision:
  > frozenset({'CAS:17417-06-0', 'PUBCHEM.COMPOUND:16235945', 'PUBCHEM.COMPOUND:10313238'}) 	(2)	{'biolink:SmallMolecule', 'biolink:MolecularMixture'}

The two cliques with 19 identifiers that have this problem are Pralidoxime/Pralidoxime chloride/Pralidoxime cation, (Z)-/Pralidoxime methyl sulfate ([PUBCHEM.COMPOUND:4884](https://pubchem.ncbi.nlm.nih.gov/compound/4884), [PUBCHEM.COMPOUND:135398747](https://pubchem.ncbi.nlm.nih.gov/compound/135398747), [PUBCHEM.COMPOUND:13548464](https://pubchem.ncbi.nlm.nih.gov/compound/135484646) and [PUBCHEM.COMPOUND:135573307](https://pubchem.ncbi.nlm.nih.gov/compound/135573307)):
> {'KEGG.COMPOUND:C07400', 'INCHIKEY:JBKPUQTUERUYQE-UHFFFAOYSA-O', 'CAS:45765-69-3', 'CHEMBL.COMPOUND:CHEMBL1420', 'UNII:P7MU9UTP52', 'GTOPDB:7597', 'HMDB:HMDB0014871', 'PUBCHEM.COMPOUND:135398747', 'MESH:C028797', 'CHEBI:8354', 'PUBCHEM.COMPOUND:135484646', 'DrugCentral:2231', 'UMLS:C0071808', 'DRUGBANK:DB00733', 'PUBCHEM.COMPOUND:4884', 'GTOPDB:4652', 'CAS:6735-59-7', 'PUBCHEM.COMPOUND:135573307', 'UNII:YV274KB8PY', 'CAS:25615-00-3'}

and Penicillin G potassium salt/Penicillin G potassium/Penicillin G ([PUBCHEM.COMPOUND:102090456](https://pubchem.ncbi.nlm.nih.gov/compound/102090456), [PUBCHEM.COMPOUND:23664709](https://pubchem.ncbi.nlm.nih.gov/compound/23664709) and [PUBCHEM.COMPOUND:5904](https://pubchem.ncbi.nlm.nih.gov/compound/5904)):
> {'PUBCHEM.COMPOUND:102090456', 'INCHIKEY:JGSARLDLIJGVTE-MBNYWOFBSA-N', 'UMLS:C0030842', 'UMLS:C0030827', 'PUBCHEM.COMPOUND:23664709', 'CHEBI:18208', 'CHEBI:17334', 'DrugCentral:2082', 'CHEMBL.COMPOUND:CHEMBL29', 'KEGG.COMPOUND:C00395', 'UNII:Q42T66VG0C', 'GTOPDB:4796', 'KEGG.COMPOUND:C05551', 'DRUGBANK:DB01053', 'PUBCHEM.COMPOUND:5904', 'HMDB:HMDB0015186', 'MESH:D010406', 'MESH:D010400', 'CAS:61-33-6', 'CAS:113-98-4'}
</details>

**Comment by cbizon** [comment]
This appears to fundamentally be a problem with InChiKey, which simply fails to recognize the difference between different compounds sometimes.

But Inchikeys are the basis of a big part of our concordance strategy, so I'm not exited about getting rid of them overall.   I'm thinking something along line lines of when inchikeys evaluate to {small molecule, molecular mixture} that we remove the inchi keys in that case and just merge by canonical smiles?  but I'm not sure we have smiles from all the sources...

**Comment by gaurav** [comment]
Result of discussion on Nov 9, 2022:
- Water should be a small molecule! But that's not an easy fix, and raises issues with how we handle conflation down the line.
- [ ] Would like to get a new Babel -- maybe for a stopgap we modify the chemical entity prefixes so we get them in the order that everything else is in.

**Comment by gaurav** [comment]
@cbizon I'm guessing that InChIKeys are important because people query them as identifiers? If not, I think we could solve some of these problems by replacing InChIKeys with InChIs -- we'd have more identifiers, but hopefully then water (small molecule) and water (molecular mixture) would be separated.

**Comment by cbizon** [comment]
Are the Inchi's different for water and hydron?   My understanding is is that inchikey is basically a hash of the inchis, so it's possible that two different inchis hash to the same key, but I'd be a little surprised.

The Inchi's (and by extension keys) are meant to be strings that map to a structure.  The InChi (not the key) is a representation of the structure, so if you have the InChi you can draw the structure.  That makes it at least a de-facto identifier, since it's a string and it's 1:1 with the entity (the structure).   

The InChiKey specifically is important for us because it is the key that is being used by EBI's UniChem to merge chemical cliques, and that is the nucleus of our approach in Babel.

**Comment by gaurav** [comment]
> Are the Inchi's different for water and hydron? My understanding is is that inchikey is basically a hash of the inchis, so it's possible that two different inchis hash to the same key, but I'd be a little surprised.

You are correct -- water and hydron both have the same InChIKey and the same InChI! I was confusing that term with canonical SMILES, which is where they differ (`O` and `[H+].[OH-]` respectively). So what I really meant to say was "what if we do all our chemical conflating with canonical SMILES?" But as long as we have to use InChiKeys anywhere, the water and hydron clique will be recombined, so I don't think that buys us anything.

One other approach we considered during last week's call was to separate _just_ the PubChem entry with the MolecularMixture as a separate thing, so we would have one SmallMolecule clique consisting of water+all the other identifiers (including any hydron identifiers from other sources) and one MolecularMixture clique consisting of just PUBCHEM hydron. We could then refine this over time by looking for other identifiers that we can recognize as molecular mixtures (whether by checking if their canonical SMILES has a '.' or looking something up in their record) and moving those into MolecularMixture. Cliques that have multiple PubChem types but not SmallMolecule+MolecularMixture specifically will revert to ChemicalEntity as they do currently.

Do you think that approach might be a good short-to-medium term fix for this issue?

**Comment by cbizon** [comment]
I think it's a decent pragmatic approach, recognizing that it's not 100% what we want.    It's worth the tradeoff in my opinion.

**Comment by gaurav** [comment]
> I think it's a decent pragmatic approach, recognizing that it's not 100% what we want. It's worth the tradeoff in my opinion.

I've implemented this in Babel now (PR #91 in progress). In most cases only a single PubChem compound is separated out as a MolecularMixture, but sometimes there are more than one, such as in the following example:

> WARNING:root:Found a clique that that contains PUBCHEM types ({'biolink:SmallMolecule', 'biolink:MolecularMixture'}). This clique will be split into a biolink:MolecularMixture ({'PUBCHEM.COMPOUND:11149677', 'PUBCHEM.COMPOUND:22836554', 'PUBCHEM.COMPOUND:4066245', 'PUBCHEM.COMPOUND:5373419'}) and a biolink:SmallMolecule ({'CAS:21679-31-2', 'UMLS:C0244965', 'CAS:17272-66-1', 'MESH:C049529', 'INCHIKEY:POILWHVDKZOXJZ-ARJAWSKDSA-M', 'PUBCHEM.COMPOUND:5460482'})

I will see how quickly I can get this Babel output up on an experimental instance and then we can play around with it some more.

**Comment by cbizon** [comment]
Nice!

**Comment by gaurav** [comment]
@cbizon Now up at https://nodenormalization-dev.apps.renci.org/docs and water is fixed again! This doesn't include the fix to #68, so the identifier prefixes are a little random for ChemicalEntity, but SmallMolecule and MolecularMixture both seem to be working well.

**Comment by gaurav** [comment]
Fixed in PR #91.
