### ISSUE TITLE
UMLS provides synonyms for individual numbers

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Babel#87]
e.g. from @hyi:

```
1,UMLS:C0227032
1,UMLS:C2323410
1,UMLS:C3495548
1,UMLS:C3496162
1,UMLS:C3496258
1,UMLS:C3496259
1,UMLS:C3496354
1,UMLS:C3853855
1 thoracic lymph node,UMLS:C1268042
1-2,UMLS:C3496355
10,UBERON:0002870
10,UMLS:C1827422
10,UMLS:C2327741
10,UMLS:C3496356
10,UMLS:C3496358
10,UMLS:C3496359
10,UMLS:C3853857
10,UMLS:C4018799
```

Should we be filtering this out?

**Comment by gaurav** [comment]
For https://uts.nlm.nih.gov/uts/umls/concept/C2323410, `1` is marked is an obsolete synonym -- is this sneaking in incorrectly?

**Comment by cbizon** [comment]
It was recently pointed out by explainer agent that "43" returned a result in name resolver.  If you look in there you can see that e.g. a bunch of these 10's are (sort of) valid.  They're things like Tooth #10 or Broadman's area 10, which maybe in a very limited space you might be able to use 10 as a synonym for.  In my opinion, they're useless for us and we should filter out anything that is a just a numeral.
